# ./python_code/api.py
import os
import random
from flask import Flask, request, render_template
from flask_restful import Resource, Api, reqparse
from flask_cors import CORS
import numpy as np
from Blade import Blade
app = Flask(__name__)
CORS(app)
api = Api(app)
@app.route("/")
def BladeList():
    Pyra = Blade("Pyra", "https://vignette.wikia.nocookie.net/xenoblade/images/4/4e/XC2-element-fire.png/revision/latest/scale-to-width-down/36?cb=20180425030957", "https://babd.wincenworks.com/wp-content/uploads/2017/12/tumblr_p1bvw1TF4g1s755fuo4_r1_1280-2.png", "https://vignette.wikia.nocookie.net/xenoblade/images/f/fd/XC2_Aegis_Sword_icon.png/revision/latest/scale-to-width-down/40?cb=20190404044917", "Pyra is a kind-hearted, mild-mannered, soft spoken young woman who desires peace among both Blades and Drivers.")
    Mythra = Blade("Mythra", "https://vignette.wikia.nocookie.net/xenoblade/images/7/71/XC2-element-light.png/revision/latest/scale-to-width-down/36?cb=20180425030958", "https://vignette.wikia.nocookie.net/p__/images/2/2b/Mythra.png/revision/latest?cb=20180517124742&path-prefix=protagonist", "https://vignette.wikia.nocookie.net/xenoblade/images/4/4c/XC2_Aegis_Sword_II_icon.png/revision/latest/scale-to-width-down/40?cb=20200426104645", "Mythra is confident in herself, reckless, and independent. She has a short temper, a rude disposition, and is not afraid to openly express her thoughts.")
    Dromarch = Blade("Dromarch", "https://vignette.wikia.nocookie.net/xenoblade/images/c/c3/XC2-element-water.png/revision/latest/scale-to-width-down/36?cb=20180425030959", "https://vignette.wikia.nocookie.net/nintendo/images/2/23/Dromarch.png/revision/latest?cb=20171102161655&path-prefix=en", "https://vignette.wikia.nocookie.net/xenoblade/images/2/2f/XC2_Twin_Rings_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230347", "Dromarch is a somber and astute old man-tiger; he does all he can to look out for Nia and preserve an air of dignity and respect both for her and those they meet. Occasionally Dromarch attempts to make jokes, which tend to fall flat.")
    Nia = Blade("Nia", "https://vignette.wikia.nocookie.net/xenoblade/images/c/c3/XC2-element-water.png/revision/latest/scale-to-width-down/36?cb=20180425030959", "https://vignette.wikia.nocookie.net/p__/images/0/09/Nia_artwork.png/revision/latest?cb=20180915200716&path-prefix=protagonist", "https://vignette.wikia.nocookie.net/xenoblade/images/c/cb/XC2_Catalyst_Scimitar_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230243", "Nia usually comes across as sarcastic and cynical, always having a witty put-down at other characters' shortcomings.")
    Roc = Blade("Roc", "https://vignette.wikia.nocookie.net/xenoblade/images/d/d0/XC2-element-wind.png/revision/latest/scale-to-width-down/36?cb=20180425030959", "https://vignette.wikia.nocookie.net/nintendo/images/d/d7/Xenoblade_Chronicles_2_-_Roc.png/revision/latest?cb=20171110045232&path-prefix=en", "https://vignette.wikia.nocookie.net/xenoblade/images/f/f5/XC2_Dual_Scythes_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230245", "Roc is proud and brusque, with excellent techniques and skill on the battlefield.")
    Poppi = Blade("Poppi", "https://vignette.wikia.nocookie.net/xenoblade/images/2/26/XC2-element-earth.png/revision/latest/scale-to-width-down/36?cb=20180425030956", "https://vignette.wikia.nocookie.net/p__/images/1/13/XC2-Poppi-Artwork.png/revision/latest?cb=20180915213526&path-prefix=protagonist", "https://vignette.wikia.nocookie.net/xenoblade/images/c/c4/XC2_Drill_Shield_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230245", "Despite being an artificial Blade, Poppi has a fully human personality and is able to feel emotion, though she speaks like a Nopon.")
    Brighid = Blade("Brighid", "https://vignette.wikia.nocookie.net/xenoblade/images/4/4e/XC2-element-fire.png/revision/latest/scale-to-width-down/36?cb=20180425030957", "https://vignette.wikia.nocookie.net/nintendo/images/a/ab/Xenoblade_Chronicles_2_-_Brighid.png/revision/latest?cb=20171107173013&path-prefix=en", "https://vignette.wikia.nocookie.net/xenoblade/images/c/cc/XC2_Whipswords_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230348", "She is polite and strong-willed. She is also very wise and is attentive to the demands of both her and Mòrag's station; however, she will defer to Mòrag's decisions in conflicts.")
    Aegaeon = Blade("Aegaeon", "https://vignette.wikia.nocookie.net/xenoblade/images/c/c3/XC2-element-water.png/revision/latest/scale-to-width-down/36?cb=20180425030959", "https://vignette.wikia.nocookie.net/xenoblade/images/a/a4/XC2_Aegaeon_Artwork.png/revision/latest?cb=20190203040017", "https://vignette.wikia.nocookie.net/xenoblade/images/3/3a/XC2_Chroma_Katana_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230243", "Aegaeon is a quiet and steadfast Blade who acts as the emperor's shield and consul. He is reserved but swift to execute his Driver's will, and has acted in the interests of the royal family of Mor Ardain for at least 500 years.")
    Pandoria = Blade("Pandoria", "https://vignette.wikia.nocookie.net/xenoblade/images/b/b1/XC2-element-electric.png/revision/latest/scale-to-width-down/36?cb=20180425030957", "https://vignette.wikia.nocookie.net/nintendo/images/7/7b/XC2_Pandoria.png/revision/latest?cb=20171107173057&path-prefix=en", "https://vignette.wikia.nocookie.net/xenoblade/images/0/02/XC2_Big_Bang_Edge_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230240", "She becomes talkative and quite cheeky, especially toward Zeke, who she teases for having bad luck, despite genuinely caring for him. She can be negligent and careless toward other's feelings, but will stick up for her friends when the need arises. Zeke calls her Pandy.")
    Godfrey = Blade("Godfrey", "https://vignette.wikia.nocookie.net/xenoblade/images/1/1c/XC2-element-ice.png/revision/latest/scale-to-width-down/36?cb=20180425030958", "https://vignette.wikia.nocookie.net/nintendo/images/2/21/Xenoblade_Chronicles_2_-_Godfrey.png/revision/latest?cb=20171110170734&path-prefix=en", "https://vignette.wikia.nocookie.net/xenoblade/images/0/0c/XC2_Shield_Hammer_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230346", "Godfrey is a confident and kind man, passionate about justice and chivalry. He believes that there is good in all the world and that evil must be punished. Godfrey is not particularly bright and is quite stuck in his beliefs.")
    Wulfric = Blade("Wulfric", "https://vignette.wikia.nocookie.net/xenoblade/images/2/26/XC2-element-earth.png/revision/latest/scale-to-width-down/36?cb=20180425030956", "https://vignette.wikia.nocookie.net/nintendo/images/d/de/Xenoblade_Chronicles_2_-_Wulfric.png/revision/latest?cb=20171110170733&path-prefix=en", "https://vignette.wikia.nocookie.net/xenoblade/images/5/58/XC2_Megalance_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230250", "Wulfric displays no obvious personality or sentience. However, possibly due to the more pro-social dispositions of his new Driver,upon being reawakened Wulfric displays a desire to be kind and is ashamed of the fear his physical appearance invokes.")
    Perceval = Blade("Perceval", "https://vignette.wikia.nocookie.net/xenoblade/images/3/3c/XC2-element-dark.png/revision/latest/scale-to-width-down/36?cb=20180425030955", "https://vignette.wikia.nocookie.net/xenoblade/images/f/f8/XC2_Perceval_Artwork.png/revision/latest?cb=20190203040052", "https://vignette.wikia.nocookie.net/xenoblade/images/3/3a/XC2_Chroma_Katana_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230243", "He has strong preferences for working alone and has trouble accepting the help of others.")
    Vale = Blade("Vale", "https://vignette.wikia.nocookie.net/xenoblade/images/3/3c/XC2-element-dark.png/revision/latest/scale-to-width-down/36?cb=20180425030955", "https://vignette.wikia.nocookie.net/nintendo/images/f/fc/Xenoblade_Chronicles_2_-_Vale.png/revision/latest?cb=20171110171313&path-prefix=en", "https://vignette.wikia.nocookie.net/xenoblade/images/5/58/XC2_Megalance_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230250", "Vale comes across as a rebellious teenager in her interactions. She is very angsty, tends to be passive aggressive, and can be abrasive.")
    Agate = Blade("Agate", "https://vignette.wikia.nocookie.net/xenoblade/images/2/26/XC2-element-earth.png/revision/latest/scale-to-width-down/36?cb=20180425030956", "https://vignette.wikia.nocookie.net/xenoblade/images/9/9c/Agate_Portrait.png/revision/latest?cb=20200424071925", "https://vignette.wikia.nocookie.net/xenoblade/images/9/9b/XC2_Greataxe_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230247", "Agate is a very helpful and protective Blade, willing to do whatever it takes to help the party. She is an avid geologist, with the grand aim of discovering a new mineral. However, she has a crippling fear of insects to the point where she will faint if one approaches her.")
    Gorg = Blade("Gorg", "https://vignette.wikia.nocookie.net/xenoblade/images/c/c3/XC2-element-water.png/revision/latest/scale-to-width-down/36?cb=20180425030959", "https://vignette.wikia.nocookie.net/xenoblade/images/2/2d/XC2_Gorg_Artwork.png/revision/latest?cb=20190203040029", "https://vignette.wikia.nocookie.net/xenoblade/images/9/9b/XC2_Greataxe_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230247", "He possesses a strong work ethic and works to be a reliable Blade for his Driver. He does possess a weakness for sweets, having a great desire to own a Patisserie if he were ever given leave from his regular duties as a Blade, and can even become distracted in conversation if a nearby dessert catches his eye.")
    Boreas = Blade("Boreas", "https://vignette.wikia.nocookie.net/xenoblade/images/d/d0/XC2-element-wind.png/revision/latest/scale-to-width-down/36?cb=20180425030959", "https://vignette.wikia.nocookie.net/xenoblade/images/5/5a/XC2_Boreas_Artwork.png/revision/latest?cb=20190203040018", "https://vignette.wikia.nocookie.net/xenoblade/images/f/f7/XC2_Bitball_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230240", "Boreas is childlike in mannerism and loves to eat, to the point where he will lick party members to see if they taste good. He is easily upset if anything prevents him from eating and has the unique ability to travel as fast as the wind, which he uses sometimes accidentally if he loses his temper.")
    Dagas = Blade("Dagas", "https://vignette.wikia.nocookie.net/xenoblade/images/4/4e/XC2-element-fire.png/revision/latest/scale-to-width-down/36?cb=20180425030957", "https://vignette.wikia.nocookie.net/xenoblade/images/5/57/XC2_Dagas_Artwork.png/revision/latest?cb=20190203040019", "https://vignette.wikia.nocookie.net/xenoblade/images/9/9b/XC2_Greataxe_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230247", "Dagas is extremely haughty and arrogant. He is convinced he is the ruler of a nation, despite Blades having no memories of their previous lives, and rationalizes his status as a Blade as a necessary burden to maintain his rule. As such, he is quick to anger at the slightest perceived disrespect and expects to be treated with reverence.")
    Kasandra = Blade("Kasandra", "https://vignette.wikia.nocookie.net/xenoblade/images/3/3c/XC2-element-dark.png/revision/latest/scale-to-width-down/36?cb=20180425030955", "https://vignette.wikia.nocookie.net/nintendo/images/a/a5/Kasandra_Artwork.png/revision/latest?cb=20181001005314&path-prefix=en", "https://vignette.wikia.nocookie.net/xenoblade/images/0/0c/XC2_Shield_Hammer_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230346", "Kasandra comes across as a very cheery young Blade, though the mask on the back of her head radiates with a dark aura. Additionally, during some specials, the mask covers her face and upon coming off, Kasandra acts as if she had no idea what happened. Kasandra considers herself very lucky, making her very unaware of the misfortune she brings to people around her.")
    Praxis = Blade("Praxis", "https://vignette.wikia.nocookie.net/xenoblade/images/c/c3/XC2-element-water.png/revision/latest/scale-to-width-down/36?cb=20180425030959", "https://vignette.wikia.nocookie.net/xenoblade/images/c/c0/XC2_Praxis_Artwork.png/revision/latest?cb=20190203040053", "https://vignette.wikia.nocookie.net/xenoblade/images/5/58/XC2_Megalance_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230250", "Praxis is shown to be kind, if a bit sassy. She becomes very friendly and supportive in behavior. She is horrified to learn that she was a criminal in her previous life.")
    Theory = Blade("Theory", "https://vignette.wikia.nocookie.net/xenoblade/images/1/1c/XC2-element-ice.png/revision/latest/scale-to-width-down/36?cb=20180425030958", "https://vignette.wikia.nocookie.net/xenoblade/images/0/07/XC2_Theory_Artwork.png/revision/latest/top-crop/width/300/height/300?cb=20190203040101", "https://vignette.wikia.nocookie.net/xenoblade/images/3/3a/XC2_Chroma_Katana_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230243", "Theory is quite cold toward others, including her Driver.")
    Perun = Blade("Perun", "https://vignette.wikia.nocookie.net/xenoblade/images/1/1c/XC2-element-ice.png/revision/latest/scale-to-width-down/36?cb=20180425030958", "https://vignette.wikia.nocookie.net/xenoblade/images/f/fa/Perun_Portrait.png/revision/latest/top-crop/width/360/height/450?cb=20200424074154", "https://vignette.wikia.nocookie.net/xenoblade/images/5/58/XC2_Megalance_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230250", "Perun is a valiant warrior, fighting relentlessly to help others. She dedicates her very existence to justice and will fight to her last breath to protect others, and will loyally follow the party who shares this sense. She is sensitive to the needs of others and will hold back if fighting all out can lead to innocent people being hurt or killed.")
    Kora = Blade("Kora", "https://vignette.wikia.nocookie.net/xenoblade/images/b/b1/XC2-element-electric.png/revision/latest/scale-to-width-down/36?cb=20180425030957", "https://vignette.wikia.nocookie.net/xenoblade/images/4/4d/XC2_Kora_Artwork.png/revision/latest?cb=20190203040041", "https://vignette.wikia.nocookie.net/xenoblade/images/f/f9/XC2_Knuckle_Claws_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230249", "Kora is chatty and emotive, loving gossip and being trendy. She is easily excited and will often talk excessively and seems thoughtless toward others.")
    Azami = Blade("Azami", "https://vignette.wikia.nocookie.net/xenoblade/images/3/3c/XC2-element-dark.png/revision/latest/scale-to-width-down/36?cb=20180425030955", "https://vignette.wikia.nocookie.net/xenoblade/images/0/0c/XC2_Azami_Artwork.png/revision/latest?cb=20190203040018", "https://vignette.wikia.nocookie.net/xenoblade/images/a/ac/XC2_Ether_Cannon_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230247", "Azami can be very possessive of her Driver. She will take rather extreme action if she senses anything suspicious.")
    Ursula = Blade("Ursula", "https://vignette.wikia.nocookie.net/xenoblade/images/1/1c/XC2-element-ice.png/revision/latest/scale-to-width-down/36?cb=20180425030958", "https://vignette.wikia.nocookie.net/xenoblade/images/8/88/XC2_Ursula_Artwork.png/revision/latest/top-crop/width/300/height/300?cb=20190203040101", "https://vignette.wikia.nocookie.net/xenoblade/images/f/f9/XC2_Knuckle_Claws_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230249", "Ursula is a very kindhearted yet soft-spoken Blade always accompanied by Beary. She enjoys singing a great deal. However, she is incredibly shy and has great difficulty bringing herself to meet new people, much less sing in front of an audience.")
    Newt = Blade("Newt", "https://vignette.wikia.nocookie.net/xenoblade/images/4/4e/XC2-element-fire.png/revision/latest/scale-to-width-down/36?cb=20180425030957", "https://vignette.wikia.nocookie.net/xenoblade/images/4/44/XC2_Newt_Artwork.png/revision/latest?cb=20190203040042", "https://vignette.wikia.nocookie.net/xenoblade/images/3/3a/XC2_Chroma_Katana_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230243", "Newt loves to fight and is incredibly excited about Titan weapons and the army of the Empire of Mor Ardain.")
    Nim = Blade("Nim", "https://vignette.wikia.nocookie.net/xenoblade/images/2/26/XC2-element-earth.png/revision/latest/scale-to-width-down/36?cb=20180425030956", "https://vignette.wikia.nocookie.net/xenoblade/images/9/9e/XC2_Nim_Artwork.png/revision/latest?cb=20190203040043", "https://vignette.wikia.nocookie.net/xenoblade/images/f/f9/XC2_Knuckle_Claws_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230249", "Nim is a cheery young woman driven by her love of nature, which she reveres above all else.")
    Sheba = Blade("Sheba", "https://vignette.wikia.nocookie.net/xenoblade/images/c/c3/XC2-element-water.png/revision/latest/scale-to-width-down/36?cb=20180425030959", "https://vignette.wikia.nocookie.net/xenoblade/images/0/03/XC2_Sheba_Artwork.png/revision/latest?cb=20190203040101", "https://vignette.wikia.nocookie.net/xenoblade/images/a/ac/XC2_Ether_Cannon_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230247", "Sheba is an extravagant Blade, having a taste for luxury and expensive items. She desires nothing more than to form an entourage of women, and so looks down on men as a means to her ends. She does not appear to be easily discouraged from her goal.")
    Vess = Blade("Vess", "https://vignette.wikia.nocookie.net/xenoblade/images/b/b1/XC2-element-electric.png/revision/latest/scale-to-width-down/36?cb=20180425030957", "https://vignette.wikia.nocookie.net/nintendo/images/9/90/Xenoblade_Chronicles_2_-_Vess.png/revision/latest?cb=20171110172833&path-prefix=en", "https://vignette.wikia.nocookie.net/xenoblade/images/f/f7/XC2_Bitball_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230240", "Vess has a very nurturing, motherly personality, providing a meaningful mother figure to her previous Driver's children and expressing a substantial desire to cook for and heal those around her. She is gentle, docile, and well-liked.")
    Adenine = Blade("Adenine", "https://vignette.wikia.nocookie.net/xenoblade/images/d/d0/XC2-element-wind.png/revision/latest/scale-to-width-down/36?cb=20180425030959", "https://vignette.wikia.nocookie.net/xenoblade/images/f/f7/XC2_Adenine_Artwork.png/revision/latest?cb=20190203040017", "https://vignette.wikia.nocookie.net/xenoblade/images/f/f9/XC2_Knuckle_Claws_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230249", "Adenine is a scholar, interested in learning and books. She speaks using a wide range of vocabulary. Additionally, she is excited at the prospect of new knowledge; the Tomes of Morytha in particular.")
    Electra = Blade("Electra", "https://vignette.wikia.nocookie.net/xenoblade/images/b/b1/XC2-element-electric.png/revision/latest/scale-to-width-down/36?cb=20180425030957", "https://vignette.wikia.nocookie.net/xenoblade/images/5/59/XC2_Electra_Artwork.png/revision/latest?cb=20190203040028", "https://vignette.wikia.nocookie.net/xenoblade/images/0/0c/XC2_Shield_Hammer_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230346", "Her best quality is perhaps her cheery, energizing personality. However, Electra is easily upset and desires to be more directly helpful.")
    Zenobia = Blade("Zenobia", "https://vignette.wikia.nocookie.net/xenoblade/images/d/d0/XC2-element-wind.png/revision/latest/scale-to-width-down/36?cb=20180425030959", "https://vignette.wikia.nocookie.net/nintendo/images/8/8c/Xenoblade_Chronicles_2_-_Zenobia.png/revision/latest?cb=20171110171128&path-prefix=en", "https://vignette.wikia.nocookie.net/xenoblade/images/9/9b/XC2_Greataxe_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230247", "While generally well meaning in what she does, Zenobia also has an incredible lust for battle and constantly seeks stronger and stronger opponents to fight.")
    Finch = Blade("Finch", "https://vignette.wikia.nocookie.net/xenoblade/images/d/d0/XC2-element-wind.png/revision/latest/scale-to-width-down/36?cb=20180425030959", "https://vignette.wikia.nocookie.net/nintendo/images/6/66/Xenoblade_Chronicles_2_-_Finch.png/revision/latest?cb=20171110045232&path-prefix=en", "https://vignette.wikia.nocookie.net/xenoblade/images/0/0c/XC2_Shield_Hammer_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230346", "Finch is extremely forgetful and airheaded. She has trouble recalling names and often forgets events as soon as they have occurred. Other than that she is sweet and cheerful, and people find her endearing.")
    Floren = Blade("Floren", "https://vignette.wikia.nocookie.net/xenoblade/images/2/26/XC2-element-earth.png/revision/latest/scale-to-width-down/36?cb=20180425030956", "https://vignette.wikia.nocookie.net/xenoblade/images/1/11/XC2_Floren_Artwork.png/revision/latest?cb=20190203040028", "https://vignette.wikia.nocookie.net/xenoblade/images/f/f7/XC2_Bitball_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230240", "Whilst Floren seems sweet and charming, he is quite manipulative and enjoys using his appearance to make people dote on him and give him things. He cares genuinely for nature, though, and is highly protective of it.")
    Herald = Blade("Herald", "https://vignette.wikia.nocookie.net/xenoblade/images/b/b1/XC2-element-electric.png/revision/latest/scale-to-width-down/36?cb=20180425030957", "https://vignette.wikia.nocookie.net/nintendo/images/6/6d/Herald_Artwork.png/revision/latest?cb=20181001194430&path-prefix=en", "https://vignette.wikia.nocookie.net/xenoblade/images/a/ac/XC2_Ether_Cannon_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230247", "Herald wants to do good, but her inability to fully control her powers hinders her efforts. While appearing calm and focused, she harbors guilt for what she has done in her previous life and is scared for what may happen if she loses control again.")
    Dahlia = Blade("Dahlia", "https://vignette.wikia.nocookie.net/xenoblade/images/1/1c/XC2-element-ice.png/revision/latest/scale-to-width-down/36?cb=20180425030958", "https://vignette.wikia.nocookie.net/xenoblade/images/9/9e/XC2_Dahlia_Artwork.png/revision/latest?cb=20190203040027", "https://vignette.wikia.nocookie.net/xenoblade/images/f/f7/XC2_Bitball_icon.png/revision/latest/scale-to-width-down/40?cb=20190405230240", "Dahlia speaks like a southern belle. She is aware of her beauty and her ability to attract others' attention. She comes across as confident and supportive of those around her. She has an interest in icesculpting.")

    BladeList = [Pyra, Mythra, Dromarch, Nia, Roc, Poppi, Brighid, Aegaeon, Pandoria, Godfrey, Wulfric, Perceval, Vale, Agate, Gorg, Boreas, Dagas, Kasandra, Praxis, Theory, Perun, Kora, Azami, Ursula, Newt, Nim, Sheba, Vess, Adenine, Electra, Zenobia, Finch, Floren, Herald, Dahlia]
    y = BladeList[random.randint(0,34)]
    return {"Blade": str(y.name), "Element": str(y.element), "Picture": str(y.picture), "Weapon": str(y.weapon), "Summary": str(y.summary)}
if __name__ == "__main__":
    app.run() 
app.run(debug=True)